# Generated by Django 5.2.13 on 2026-05-11 17:37

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('id_card', 'ID Card'), ('books', 'Books'), ('keys', 'Keys'), ('wallet', 'Wallet / Purse'), ('bag', 'Bag / Backpack'), ('jewellery', 'Jewellery'), ('sports', 'Sports Equipment'), ('other', 'Other')], default='other', max_length=30)),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=10)),
                ('date_of_incident', models.DateField(help_text='Date when item was lost/found')),
                ('location', models.CharField(help_text='e.g. Library 2nd floor, Hostel C', max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type'], name='items_item_item_ty_048ead_idx'), models.Index(fields=['status'], name='items_item_status_819478_idx'), models.Index(fields=['category'], name='items_item_categor_db7f55_idx'), models.Index(fields=['location'], name='items_item_locatio_896340_idx'), models.Index(fields=['item_type', 'status'], name='items_item_item_ty_fb9ed8_idx')],
            },
        ),
    ]
